# fly.toml app configuration file generated for duy-memos on 2023-05-11T17:49:43+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "duy-memos"
primary_region = "sin"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  image = "hu3rror/memos-fly:latest"

[env]
  DB_PATH = "/var/opt/memos/memos_prod.db"
  LITESTREAM_REPLICA_BUCKET = "app-memos"
  LITESTREAM_REPLICA_ENDPOINT = "s3.us-west-004.backblazeb2.com"
  LITESTREAM_REPLICA_PATH = "memos_prod.db"

[[mounts]]
  source = "memos_data_machines"
  destination = "/var/opt/memos"
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 5230
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
